<?php // æøåÆØÅ UTF-8 uden BOM

$keywords = array_unique(array(
    'scootergrisen','scootergrisen.dk'
   ,'scooter','scootere'
   ,'knallert','knallerter'
   ,'moped','gas scooter'
   ,'gy6','139qm','139qma','139qmb','1p39qm','1p39qma','1p39qmb','139fm','139fma','139fmb'
   ,'4t','4 t','4 takt','fire takt','takt','stroke','4 stroke','four stroke'
   ,'4 takt motor','4 takt scooter','motor'
   ,'25','30','45','50'
   ,'kmt','km/t','kmh','km/h'
   ,'cc','ccm','ccm3','ccm 3','cm3','cm 3','volume','kubik','kubic'
   ,'data','specifikation','specifikationer'
   ,'manual','manualer'
   ,'brugermanual','servicemanual'
   ,'bruger manual','service manual'
   ,'owner manual','owners manual','workshop manual'
   ,'el diagram','el-diagram','el diagrammer'
   ,'pris','priser'
   ,'hastighed'
   ,'køling'
   ,'boring'
   ,'slaglængde'
   ,'ventil','ventiler','ventil justering'
   ,'kompression'
   ,'tomgang'
   ,'tændrør'
   ,'benzintank'
   ,'benzin forbrug','km/l','kml','mpg'
   ,'fælg'
   ,'dæk','dæk tryk','slangeløs','slangeløse','slangeløst'
   ,'affjedring'
   ,'bremse','bremser'
   ,'batteri'
   ,'generator'
   ,'tændingssystem'
   ,'elstart','el start','elstarter','el starter'
   ,'lys,','pære','pærer','forlys','baglys','positionslys','blinklys'
   ,'oplade','oplader'
   ,'controller'
   ,'transmission','cvt','variator','variomatic','reduktions gear','reduktionsgear'
   ,'udstødning'
   ,'euroemission','euro emission'
   ,'luftfilter'

   ,'forum'
   ,'nyheder'
   ,'introduktion'
   ,'galleri'
   ,'download'
   ,'upload'
   ,'links'
   ,'kontakt'

   ,'oplysninger'
   ,'benzin'
   ,'bøger og blade'
   ,'forsikring'
   ,'køb af scooter'
   ,'olie'
   ,'omregn','udregn'
   ,'registrering','nummerplade','stelnummer','motornummer','fabrikationsplade','komponentmærkningsskilt'
   ,'smørelse','væsker'
   ,'steder i danmark', 'forhandler', 'forhandlere', 'importør'
   ,'teoriprøve'
   ,'tilkøring'
   ,'typegodkendelse'
   ,'tyverisikring'
   ,'værktøj'

   ,'scooterens dele'
   ,'affjedring'
   ,'begrænsninger','begrænset','begrænsning','ubegrænset'
   ,'benzintank'
   ,'bremser'
   ,'brændstofindsprøjtning'
   ,'dæk','lap','lapning'
   ,'elektrisk'
   ,'karburator'
   ,'kickstarter'
   ,'køling'
   ,'luftfilter','udstødning'
   ,'motor'
   ,'reservedelstegninger'
   ,'speedometer'
   ,'starterdrev'
   ,'støtteben'
   ,'transmission'
   ,'tænding'
   ,'tændrør'

   ,'service'
   ,'bremser'
   ,'dæk'
   ,'elektrisk'
   ,'fejlfinding'
   ,'forlygte'
   ,'kabler'
   ,'karburator'
   ,'luftfilter', 'udstødning'
   ,'motor'
   ,'olie'
   ,'serviceskemaer'
   ,'tilspændingsmoment'
   ,'transmission'
   ,'tænding'
   ,'tændrør'
   ,'ventiler'

   ,'specielt'
   ,'2 takt scootere'
   ,'pgo'
   ,'elektriske scootere'
   ,'giantco e-buddy'
   ,'giantco el diagram'
   ,'kymco super 8'
   ,'optimate 4'
   ,'peugeot e-vivacity'
   ,'puch'
   ,'vinterråd'

   ,'fremtiden'
   ,'brændselscelle'
   ,'fremtidens scootere'

   ,'scootermærker'
   ,'a2b'
      ,'metro'
   ,'agm'
      ,'bella'
      ,'bella extra'
      ,'bella gt'
      ,'bella pimp','bella pimped'
      ,'classic'
      ,'fashion'
      ,'hybrid'
      ,'nano'
      ,'vintage'
   ,'amp','amp electro','strømpil'
      ,'velocity'
      ,'ørsted'
   ,'apollo','orion','aragon','offroad','off road','off-road','motard'
      ,'29','A29E50M30'
      ,'30','A30E50M30'
      ,'36','A36A50M30','A36A50M','RX36ARA'
   ,'aprilia'
      ,'scarabeo','scarabeo 4T'
      ,'sportcity one'
   ,'avanti'
      ,'BT49QT-9N'
      ,'classic sport'
      ,'eagle'
      ,'nostalgi'
      ,'rocky'
      ,'sport'
      ,'wolf', 'wulf'
   ,'baotian'
      ,'bttdm500-3'
      ,'city'
      ,'classic' ,'classic sport'
      ,'f3'
      ,'rebel'
      ,'retro'
      ,'rocky'
      ,'sport'
      ,'supermoto'
      ,'BT49QT'    ,'BT50QT'
      ,'BT49QT-7'
      ,'BT49QT-8'
      ,'BT49QT-9'  ,'BT50QT-9'
      ,'BT49QT-9D'
      ,'BT49QT-10'
                   ,'BT50QT-11'
      ,'BT49QT-12' ,'BT50QT-12'
      ,'BT49QT-20'
   ,'busetto'
      ,'ecc-800','ecc800','ecc 800'
      ,'Lynx 388-2','ABAT ZQTD-388-2','ZQTD-388-2'
   ,'cpi'
      ,'aragon'
      ,'formula'
      ,'GTR'
      ,'hussar'
      ,'oliver'
      ,'popcorn'
      ,'supercross'
      ,'supermoto'
   ,'earthenergy'
      ,'city'
      ,'emma'
      ,'italia'
      ,'retro'
      ,'whisper'
   ,'ebretti'
      ,'518'
   ,'ego'
      ,'helio'
   ,'evt'
      ,'3w','325','345'
      ,'168'
      ,'4000e'
   ,'e-ton','matra'
      ,'e-mo'
   ,'giantco'
      ,'e-Buddy','e Buddy','HY1000QTD'
      ,'g-Buddy','g Buddy','HY50QT-3'
      ,'sprint','sprint','sprint sport','HY50QT-3'
      ,'stealth','HY50QT-10'
      ,'venus','HY50QT-6'
   ,'gilera'
      ,'DNA'
      ,'ICE'
      ,'RCR'
      ,'runner'
         ,'runner DD'
         ,'runner SP'
         ,'runner PureJet'
      ,'SMT'
      ,'stalker'
         ,'stalker naked'
      ,'storm'
      ,''
   ,'hero majestic'
      ,'vogue'
   ,'honda'
      ,'dax','ST50'
      ,'vision','NSC'
      ,'zoomer','Ruckus','NPS 50','NPS50','AF66E'
   ,'kinroad'
      ,'chopper','XT50Q-A'
   ,'kreidler'
      ,'hiker amaze', 'RMC-E'
   ,'kymco'
      ,'agility','CK50QT-5','agility sport','aglity race'
      ,'like'
      ,'super 8','CK50QT-6'
   ,'longjia', 'VGA'
      ,'digita', 'firefly', 'LJ50QT-2L'
      ,'exactly', 'LJ50QT-K'
      ,'grido', 'LJ50QT-H'
      ,'mover', 'LJ50QT-6'
      ,'versus', 'LJ50QT-F'
   ,'luyuan'
      ,'YMO-6BTL-A'
   ,'malaguti'
      ,'ciak','ciak master'
   ,'nicom', 'elvin'
      ,'TDR48K15'
   ,'motormania','motor mania'
      ,'bella'
      ,'desire','rx8'
      ,'fino'
      ,'s1','racing s1','MM50QT-21'
      ,'s2','racing s2'
      ,'speedy'
      ,'spirit'
   ,'norsjö'
      ,'carrier'
         ,'carrier 4 stroke'
         ,'carrier electronic'
   ,'peugeot'
      ,'kisbee'
      ,'scoot elec','scoot','elec','scoot\'elec'
      ,'tweet'
      ,'v-clic','Jinan Qing Qi'
      ,'vivacity','vivacity 4t'
   ,'pgo'
      ,'big max','big max 12','big max sp','PS-50'
      ,'comet','E1'
      ,'dr big'
      ,'galaxy'
      ,'g-max','gmax','M2-50'
      ,'hot','hot 12','hot sp'
      ,'its magic'
      ,'libra', 'BF-50','B1'
      ,'ligero'
      ,'new ligero','PA-50'
      ,'ligero rs','PA-50'
      ,'p3'
         ,'knallert','PM-50'
         ,'magnum','CP-50'
      ,'pmx'
      ,'pmx sport','PM-50'
      ,'pmx naked', 'PM-50DN'
      ,'tornado'
      ,'t-rex','trex','t-rex sp','CP-50'
      ,'trike'
      ,'x-hot','xhot', 'BF-50','B2'
   ,'piaggio'
      ,'fly','fly 4t'
      ,'liberty','liberty 4t'
      ,'zip','zip 4t'
   ,'qingqi'
      ,'fizz','QM50QT-2'
   ,'regal raptor'
      ,'dd50','dd50e','dd50qe-3','dd50e-2'
   ,'rieju'
      ,'pacific', 'FR Evasion Racing Edition', 'YH50QT'
   ,'romet'
      ,'ogar 900 r-racing','Longbo LB50Q-5'
   ,'sachs'
      ,'madass','madass mark II'
      ,'saxy'
   ,'scoopie'
      ,'scoopie 450w','TDR946Z'
      ,'scoopie 500w','Luyuan LEV006 ME'
      ,'retro 64'
      ,'scoopie 1500w','Swei swen king','Xinling TXD1500c','SW0002'
      ,'txd500','Xinling TXD500a'
      ,'txd800','Xinling TXD800a','Swei Swen Prince'
   ,'skyteam'
      ,'ace'
      ,'bat.one'
      ,'cobra'
      ,'dax','st50-6'
      ,'gorilla'
      ,'monkey','st50-8'
      ,'pbr','st50'
      ,'skymax'
      ,'skymax club'
      ,'skymax pro'
      ,'skymax special edition'
      ,'st50-3'
      ,'t-rex','st50-11'
   ,'swap'
      ,'swap 2','swap-l','swap l'
      ,'swap 3'
   ,'sym','san yang motor','sanyang motor','san-yang motor'
      ,'cello','allo','AJ05W'
      ,'fiddle','fiddle II','AW05W'
      ,'fiddle 3 hjul'
      ,'jet 4','AD05W'
      ,'mio','HU05'
      ,'orbit','symply','AV05W','orbit II S','AE05W'
      ,'orbit 3 hjul'
      ,'symphony','AY05W','symphony SR','AZ05W'
   ,'texas'
      ,'chili','BT49QT-12'
      ,'city','City 50-4'
      ,'comfort','Comfort 50-4X'
      ,'flash','Flash 30-4','BT50QT-9','s30','x30'
      ,'free','Free 50-4'
      ,'street','Street 50-4X'
      ,'whisper'
   ,'tms','trend motor sports'
      ,'classic'
      ,'offroad'
      ,'retro','BT49QT-11da'
      ,'s3','BT49QT-9d'
      ,'sprint','BT49QT-12C'
      ,'z2','QM50QT-2'
   ,'vespa'
      ,'LX','LX 50','LX 50 4T'
   ,'yamaha'
      ,'EC-03'
      ,'giggle','vox','C3','XF50E'
      ,'neos','neos 4t','YN50F'
   ,'yamasaki'
      ,'ym50gys','kingway'
      ,'ym50-8b'
   ,'yiben','danscooter'
      ,'danger','YB50QT-19'
      ,'easy','YB50QT-3D'
      ,'hunter','YB50QT-15C'
      ,'matrix','YB50QT-9H'
      ,'skywalk','YB50QT-15C'
   ,'zongshen'
      ,'zs50q-3'
   ,'andre mærker'
      ,'benda scoot'
      ,'benmal LB-852'
      ,'city scooter','freak','city scooter freak','BT49QT-12'
      ,'hooper one'
      ,'listo','ZY50QT-7'
      ,'pexma','KD50QT-4','PM50QT-4'
      ,'rmc','zan zara'
      ,'shineray'
      ,'stranger x fight','stranger x-fight','YY50QT'
      ,'superbike','super bike','superbike xt50qt-2','xt50qt-2'
      ,'tisong TM-300'
      ,'veken','vk-m50'
      ,'xmotos'
         ,'xb31'
         ,'xb81'
      ,'zero','zero-e','zero e'

));

return $keywords;

?>